### ISSUE TITLE
complete first small truss example (von Mises) 

### ISSUE THREAD

**Issue by jorgepz** [jorgepz/FEMAssembler.jl#2]
- [x] get it working
 - [x] add it to tests
 - [x] add CI

**Comment by lucaferranti** [comment]
the small truss example is the one currently in the ILA docs?

**Comment by jorgepz** [comment]
Not exactly. By the moment it is a simpler problem called von mises truss ... Based on this https://onsas.github.io/ONSAS.m/dev/staticVonMisesTruss/ . The von mises problem has a simple analytic solution. Then it is a good start. After we can switch for the skalna problem...
